In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.76067373,  0.8829626 , -0.13530677, -0.95203646,  0.48428414,
        0.69269265,  0.9257996 , -0.37096071])

In [6]:
y

array([ 0.32031596, -1.07675642, -0.49200407, -0.58703412, -0.36599777,
       -0.94214014,  0.98396246, -0.38702267])

In [7]:
np.maximum(x,y)

array([ 0.76067373,  0.8829626 , -0.13530677, -0.58703412,  0.48428414,
        0.69269265,  0.98396246, -0.37096071])

In [8]:
arr = np.random.randn(7) * 5

In [9]:
arr

array([ 0.17169117, -3.09394363,  3.1265866 , -0.09925926, -1.90945516,
        0.80105766, -5.11671451])

In [10]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.17169117, -0.09394363,  0.1265866 , -0.09925926, -0.90945516,
        0.80105766, -0.11671451])

In [11]:
whole_part

array([ 0., -3.,  3., -0., -1.,  0., -5.])

In [12]:
arr

array([ 0.17169117, -3.09394363,  3.1265866 , -0.09925926, -1.90945516,
        0.80105766, -5.11671451])

In [13]:
np.sqrt(arr)

C:\Users\Seungyun\AppData\Local\Temp\ipykernel_22128\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([0.41435633,        nan, 1.76821566,        nan,        nan,
       0.89501825,        nan])

In [14]:
arr

array([ 0.17169117, -3.09394363,  3.1265866 , -0.09925926, -1.90945516,
        0.80105766, -5.11671451])

In [15]:
np.sqrt(arr,arr)
arr

C:\Users\Seungyun\AppData\Local\Temp\ipykernel_22128\3432068196.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([0.41435633,        nan, 1.76821566,        nan,        nan,
       0.89501825,        nan])

In [16]:
np.log(arr)

array([-0.88102898,         nan,  0.56997093,         nan,         nan,
       -0.11091117,         nan])

In [17]:
np.add(x,y)

array([ 1.08098969, -0.19379382, -0.62731084, -1.53907058,  0.11828637,
       -0.24944749,  1.90976206, -0.75798338])