In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.66520831, -1.01959453,  0.36667175, -0.92533751, -0.22027948,
       -0.52700507, -0.48970401, -0.21834022])

In [7]:
y

array([-0.81081756,  0.23837337, -1.34040448, -1.14985659, -1.25743303,
       -0.3376129 , -0.4429583 , -0.17570922])

In [9]:
np.maximum(x,y)

array([-0.66520831,  0.23837337,  0.36667175, -0.92533751, -0.22027948,
       -0.3376129 , -0.4429583 , -0.17570922])

In [10]:
arr = np.random.randn(7) * 5

In [11]:
arr

array([12.88138949, -1.84692021, -0.67063525, 11.36453571, -2.2013572 ,
       -1.96351832,  0.93157661])

In [12]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.88138949, -0.84692021, -0.67063525,  0.36453571, -0.2013572 ,
       -0.96351832,  0.93157661])

In [13]:
whole_part

array([12., -1., -0., 11., -2., -1.,  0.])

In [14]:
arr

array([12.88138949, -1.84692021, -0.67063525, 11.36453571, -2.2013572 ,
       -1.96351832,  0.93157661])

In [15]:
np.sqrt(arr)

C:\Users\Seungyun\AppData\Local\Temp\ipykernel_17892\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([3.58906527,        nan,        nan, 3.3711327 ,        nan,
              nan, 0.96518216])

In [16]:
arr

array([12.88138949, -1.84692021, -0.67063525, 11.36453571, -2.2013572 ,
       -1.96351832,  0.93157661])

In [17]:
np.sqrt(arr,arr)
arr

C:\Users\Seungyun\AppData\Local\Temp\ipykernel_17892\3432068196.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([3.58906527,        nan,        nan, 3.3711327 ,        nan,
              nan, 0.96518216])

In [18]:
np.log(arr)

array([ 1.2778918 ,         nan,         nan,  1.2152488 ,         nan,
               nan, -0.03543843])

In [19]:
np.add(x,y)

array([-1.47602587, -0.78122116, -0.97373273, -2.07519409, -1.47771251,
       -0.86461797, -0.93266231, -0.39404944])